### ISSUE TITLE
Static page cache not cleared

### ISSUE THREAD

**Issue by mathiasoem** [duncanmcclean/runway#166]
### Bug Description

When static caching is enabled, changes to runway entries (via the CP) are not reflected on the frontend. 
This might be a specific issue on my site. Just want to make sure that static caching is supported before digging deeper in to this. Non runway resources are being purged just fine.

### Steps to reproduce

1. Enable static caching (strategy: half)
2. Create entry
3. View entry
4. Edit entry
5. View entry - changes are not visible
6. Clear static cache
7. View entry - changes are now visible

### Environment

Laravel Version: 9.29.0
PHP Version: 8.0.22
Composer Version: 2.3.8
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Scout: meilisearch
Session: file

Statamic
Addons: 5
Antlers: runtime
Version: 3.3.36 PRO

Statamic Addons
doublethreedigital/runway: 2.5.1
elvenstar/statamic-meilisearch: 1.1.0
rias/statamic-redirect: 2.4.0
spatie/statamic-responsive-images: 2.13.1
statamic/seo-pro: 3.1.0

**Comment by duncanmcclean** [comment]
Is this when using Runway's Routing feature?

**Comment by mathiasoem** [comment]
Yes

**Comment by duncanmcclean** [comment]
Fab, I'll take a look when I can 👍

**Comment by mathiasoem** [comment]
@duncanmcclean Thanks for the quick fix! You might consider adding something like this, to just invalidate the entry being saved:

`app(Cacher::class)->invalidateUrl($uri, rtrim(Statamic\Facades\URL::getSiteUrl(), '/'));`

**Comment by duncanmcclean** [comment]
No worries!

I’m just doing it the same way Statamic does it internally.

**Comment by mathiasoem** [comment]
I do think that Statamic does both?

In Statamic\StaticCaching\DefaultInvalidator on line 62:

```
protected function invalidateEntryUrls($entry)
    {
        $entry->descendants()->push($entry)->each(function ($entry) {
            if ($url = $entry->absoluteUrl()) {
            ray(...$this->splitUrlAndDomain($url));
            ray($this->cacher);
                $this->cacher->invalidateUrl(...$this->splitUrlAndDomain($url));
            }
        });
        
        $this->cacher->invalidateUrls(
            Arr::get($this->rules, "collections.{$entry->collectionHandle()}.urls")
        );
    }
```

**Comment by duncanmcclean** [comment]
Does the implemented solution not work for you?

**Comment by mathiasoem** [comment]
It works, but it invalidates all entries when saving. And as my resource scheme is "/{slug}" (client requirement) it means that every page on my site is invalidated whenever I make a change.

By implementing the single url invalidation it only invalidates the entry being saved.

**Comment by duncanmcclean** [comment]
Ah gotcha!

**Comment by duncanmcclean** [comment]
^ The model's own URI will now be invalidated on save, in addition to any rules you have setup in the `static_caching.php` config file.
