### ISSUE TITLE
Save button disappears on small devices

### ISSUE THREAD

**Issue by jonatanalvarsson** [duncanmcclean/runway#172]
### Description

Thanks for a great addon!

When editing a Runway post on small devices (below 768px width) the "Save" button becomes hidden and thus it's impossible to save the post.

The wrapping div has css classes `hidden md:flex` so this is expected. And the same thing actually happens when you edit a standard Statamic collection entry. However, in that case there is another "Save" button at the bottom of the page that becomes visible at the same time (`md:hidden flex`). It would be nice if Runway works in the same way.

### Steps to reproduce

1. Edit a Runway post.
2. Adjust the browser window to 768 px width or smaller.
3. The Save button disappears and there is no way to save the post.

### Environment

Environment
Application Name: ...
Laravel Version: 9.36.4
PHP Version: 8.1.11
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
URL: ...
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: redis

Statamic
Addons: 4
Antlers: runtime
Version: 3.3.48 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.0
aryehraber/statamic-logbook: 2.1.0
doublethreedigital/runway: 2.5.3
jonassiewertsen/statamic-livewire: 2.9.0

**Comment by duncanmcclean** [comment]
Thanks for reporting this - I'll take a look this weekend!

**Comment by jonatanalvarsson** [comment]
Great! Thanks!

**Comment by jonatanalvarsson** [comment]
Awesome! Thank you!
