### ISSUE TITLE
Sidebar popping in and out of tab format

### ISSUE THREAD

**Issue by JKHarley** [duncanmcclean/runway#173]
### Description

The sidebar is popping in and out of tab format at around 1220x924px on a resource.

https://www.loom.com/share/9d166d5f15c54e25a6a6258b26350d45

As shown in the Loom I have tried this with the same amount of tabs within a resource which seems to work fine.

### Steps to reproduce

1. Have a resource with a sidebar (may also need 2+ tabs)
2. Resize the windo to 1220x924px
3. Watch the magic happen

### Environment

Environment
Laravel Version: 9.21.6
PHP Version: 8.1.8
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.33 PRO

Statamic Addons
doublethreedigital/runway: 2.5.3

**Comment by duncanmcclean** [comment]
Sorry mate, I can't seem to reproduce on my sandbox site.

When you can, would you be able to push up the changes with Runway installed onto a branch so I can pull it down to test with? Thanks 😄

**Comment by duncanmcclean** [comment]
I'm going to close this for now - if you're able to reproduce it, lemme know the branch and I'll re-open and take a further look.
