### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by igmltd** [duncanmcclean/runway#199]
### Description

When attempting to install, getting this error below.  

Using version ^2.6 for doublethreedigital/runway
./composer.json has been updated
Running composer update doublethreedigital/runway
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/annotations[1.13.0, ..., 1.13.x-dev] require doctrine/lexer 1.* -> found doctrine/lexer[v1.0, ..., 1.3.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doctrine/annotations[1.14.0, ..., 1.14.x-dev] require doctrine/lexer ^1 || ^2 -> found doctrine/lexer[v1.0, ..., 1.3.x-dev, 2.0.0, 2.0.x-dev, 2.1.0, 2.1.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - friendsofphp/php-cs-fixer[v3.0.0-beta.1, ..., v3.0.0-beta.2] require composer/xdebug-handler ^1.4 -> found composer/xdebug-handler[1.4.0, ..., 1.4.x-dev] but the package is fixed to 3.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - friendsofphp/php-cs-fixer[v3.0.0-rc.1, ..., v3.4.0] require composer/xdebug-handler ^2.0 -> found composer/xdebug-handler[2.0.0, ..., 2.0.x-dev] but the package is fixed to 3.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doublethreedigital/runway[v2.6.0, ..., 2.x-dev] require friendsofphp/php-cs-fixer ^3.0 -> satisfiable by friendsofphp/php-cs-fixer[v3.0.0-beta.1, ..., v3.13.2].
    - friendsofphp/php-cs-fixer[v3.5.0, ..., v3.13.2] require doctrine/annotations ^1.13 -> satisfiable by doctrine/annotations[1.13.0, ..., 1.14.x-dev].
    - Root composer.json requires doublethreedigital/runway ^2.6 -> satisfiable by doublethreedigital/runway[v2.6.0, ..., 2.x-dev].

### Steps to reproduce

composer require doublethreedigital/runway

### Environment

Environment
Application Name: Laravel
Laravel Version: 9.48.0
PHP Version: 8.1.5
Composer Version: 2.3.3
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 PRO

**Comment by duncanmcclean** [comment]
Looks like there's a conflict with your other dependencies when you're trying to install Runway - this isn't *really* a Runway bug so I'm going to close this issue. 

Maybe try adding the `-W` parameter` to the end of the command to see if it helps?
