### ISSUE TITLE
Action::run() gets passed a wrong collection for $items

### ISSUE THREAD

**Issue by andelwebsolutions** [duncanmcclean/runway#231]
### Description

The $items collection in a Statamic action class contains incorrect models. For example, I select 50 models in the CP and run the action, the $items collection contains 50 models with an ID of 1.

The selection is passed correctly from the Statamic front-end, so it it defenitely something runway-related.

I currently use the snippet below to bypass this bug:

```
$selection = json_decode(request()->getContent())->selections;
$items = User::find($selection);
```

This bug also occurs on default actions such as delete.

### Steps to reproduce

1. (Optional) Create a custom action
2. Make a selection and run the action
3. dd($items) in the run function of the action.

### Environment

**Environment**
Application Name: XXXXXX
Laravel Version: 9.40.1
PHP Version: 8.2.1
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: XXXXXX
Maintenance Mode: OFF

**Cache**
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

**Drivers**
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

**Statamic**
Addons: 4
Antlers: runtime
Version: 3.3.56 PRO

**Statamic Addons**
doublethreedigital/runway: 2.6.7
mitydigital/iconamic: 1.1.1
octoper/statamic-blade-components: 2.0.0
statamic/eloquent-driver: 1.1.0

**Comment by duncanmcclean** [comment]
Sorry, I can't reproduce this issue in my sandbox site. I get the models through that I selected.

Are you able to reproduce in a fresh site?

**Comment by artemverbo** [comment]
Hi! Having the same issue, what I believe is going on is problem exists only in the case of custom ordered models.

For example I have an order flipped to default one:
```
'order_by' => 'created_at',
'order_by_direction' => 'DESC',
```

And then when I apply the action, for the first item in CP list, it actually is applied to the very last one.

**Comment by duncanmcclean** [comment]
I have ordering setup on one of my resources, I still can't reproduce it there. 

Are you both on the latest version of Runway (v4.2)?

**Comment by artemverbo** [comment]
@duncanmcclean you are right, sorry for the silly comment! The latest version fixes the issue, I was actually on 2.x from a few months ago when started working on a feature. Thank your for your prompt help and overall an awesome and super useful package!

**Comment by duncanmcclean** [comment]
No worries - glad it's fixed after updating!
