### ISSUE TITLE
Need help displaying Users/relationships in CP

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/runway#234]
### Discussed in https://github.com/duncanmcclean/runway/discussions/232

<div type='discussions-op-text'>

<sup>Originally posted by **jorisvan-ons** March  9, 2023</sup>
I have two fields defined as follows:
```
 [
      'handle' => 'user',
      'field' => [
          'display' => 'User',
          'type' => 'users',
      ],
  ],
```
and 
```
 [
     'handle' => 'subscription_id',
     'field' => [
         'resource' => 'subscription',
         'display' => 'Subscription',
         'type' => 'belongs_to'
     ],
 ],
```
The user fields shows this in the CP:
```
[[ { "id": 2, "title": "Norberto O'Kon", "edit_url": "https://{{ URL }}/cp/users/2/edit", "published": null } ]](https://{{ URL }}/cp/runway/subscription/98a53939-3715-42e2-82d9-8b7890c04233)
```

and the subscription is showed like this:
```
[[ { "id": 1, "title": [], "edit_url": "https://{{ URL }}/cp/runway/subscription/98a53939-3715-42e2-82d9-8b7890c04233" } ]](https://{{ URL }}/cp/runway/payment/1)
```

I've been searching the documentation and source code but I cannot figure out how to configure that it only shows the title attribute (and how to specify what the title should be). Can anyone help here?</div>

**Comment by duncanmcclean** [comment]
Hey @jorisvan-ons, 

I've converted this into an issue as it sounds like a bug! I've had a look but sadly I'm unable to replicate this issue myself...

Would you be able to check that you're on the latest version? Also, could you try running `php artisan vendor:publish --tag=runway` to re-publish Runway's JavaScript assets?

If neither of those fix the issue - would you be able to try in a fresh, barebones site and see if the issue crops up there too. If so, happy to take a look at the site.

**Comment by jorisvan-ons** [comment]
Yes I am on 4.2.2 and publishing the vendor stuff didn't work.

**Comment by duncanmcclean** [comment]
Would you be able to try in a fresh, barebones site and see if the issue crops up there too? If it does, then please give me access to that fresh site and I can take a look.
