### ISSUE TITLE
A request to much?

### ISSUE THREAD

**Issue by freshface** [duncanmcclean/runway#238]
### Description

Could it be runway is doing two requests?
One is without the columns and the other one is with the columns?

Screenshot: https://cln.sh/LhjQHZW2F0wfXPSZkxqS

Also the request fith the fields also fetches all the columns: https://cln.sh/rbbxdnL7JS9z8J8SXGBr

### Steps to reproduce

See xhr requests in console.

### Environment

Environment
Application Name
Laravel Version: 9.52.5
PHP Version: 8.1.17
Composer Version: 2.2.18
Environment: local
Debug Mode: ENABLED
URL: garagevanhulle.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
doublethreedigital/runway: 4.2.2
studio1902/statamic-peak-browser-appearance: 1.0
studio1902/statamic-peak-commands: 1.27
studio1902/statamic-peak-seo: 1.7
studio1902/statamic-peak-tools: 2.5

**Comment by duncanmcclean** [comment]
Yes, we shouldn't need to be doing more than one request here. I'll take a look whenever I have some time - I'd also accept a PR that fixes it.
