### ISSUE TITLE
User fieldtype shows stringified user instead of the user's name on CP listings

### ISSUE THREAD

**Issue by MtDalPizzol** [duncanmcclean/runway#277]
### Description

When adding a `users fieldtype` to a resource, and showing that column on a listing, the user column gets a stringified version of the user instead of showing the user name.

![image](https://github.com/duncanmcclean/runway/assets/3843774/8260cd6d-3d38-487f-9c7e-2b17178edff9)

### Steps to reproduce

1. Create a resource that have a `user_id` column.
2. Add a `users fieldtype` to the resource diagram with `user_id` as handle.
3. Set the max number of users to 1 on the field.
4. Make sure the field is listable.
5. List the the user column on the resource listing.

### Environment

Laravel 9.52
Statamic 4.2
Runway 5.0.5

I'm actually running my own fork of Runway, but I've updated it with all the work in the 5.x branch, installed the dependencies, built the frontend scripts and reinstalled my local copy into the project as dev-main. You can [checkout the for here](https://github.com/MtDalPizzol/runway).

**Comment by duncanmcclean** [comment]
Sorry, I'm unable to replicate this issue myself. 

<img width="1021" alt="image" src="https://github.com/duncanmcclean/runway/assets/19637309/f4df0f39-039d-4d81-83df-6282e48945ed">

Would you be able to switch your fork of Runway to the "real" version of Runway and see if that helps the issue? If not, can you create a sandbox site that I can pull down & test with?

**Comment by MtDalPizzol** [comment]
Hmmmm.... It looks like there's something wrong with this specific resource. I'm trying to figure it out. But anything on the first column on the listing is getting this behavior.

**Comment by MtDalPizzol** [comment]
If I can confirm anything, is that **any relationship field** is getting this behavior **when listed as the first column**.

Check it out: here, I have a date as the first column. The **Usuário** is a `users fieldtype`, while **Checkout** and **Plan** use `BelongsTo fieldytpe`.

![image](https://github.com/duncanmcclean/runway/assets/3843774/dd3a5e5e-d7fc-41b9-a6b4-b92dff5d6eba)

Now, if I try to put **Usuário**, **Plano** or **Checkout** at the first column, here's the result:

![image](https://github.com/duncanmcclean/runway/assets/3843774/0a0e30c5-1201-401c-b8b9-597107b2f8fb)

![image](https://github.com/duncanmcclean/runway/assets/3843774/1e8df590-2c01-4033-bff3-48bcf07b38c9)

![image](https://github.com/duncanmcclean/runway/assets/3843774/bfa2da06-8579-497d-8dca-f6627966235f)

**Comment by duncanmcclean** [comment]
Fixed in https://github.com/duncanmcclean/runway/releases/tag/v5.0.7
