### ISSUE TITLE
Call to undefined method App\Models\Model_Name::site()

### ISSUE THREAD

**Issue by Camaendir** [duncanmcclean/runway#299]
### Description

When searching for a runway resource, the following exception is thrown: https://flareapp.io/share/J7onpDVP

### Steps to reproduce

1. Create a runway resource (company in this case)
2. Make it searchable by adding it to the statamic search config
3. try to search for it

### Environment

Environment
Application Name: Statamic
Laravel Version: 9.52.10
PHP Version: 8.2.8
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: avl_mvp.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.1 Solo

Statamic Addons
doublethreedigital/runway: 5.0.10

**Comment by Camaendir** [comment]
I could resolve it by adding the following method to my (company) model:
```
static function site(){
        return \Statamic\Facades\Site::current();
    }
 ```

**Comment by duncanmcclean** [comment]
Can you share your Runway config & search config?

**Comment by duncanmcclean** [comment]
I'm unable to replicate this issue myself when searching for Runway models, so I'm going to close this issue.

If you're still seeing this issue, please share your `runway.php` config file along with your `search.php` config file and I can take another look.
