### ISSUE TITLE
Can't save model when there's a custom field

### ISSUE THREAD

**Issue by edalzell** [duncanmcclean/runway#331]
### Description

I have a custom field that is a button. There is no corresponding field in the DB.

When you try to save, you get a "missing field" DB error.

At a minimum, it should not try to save custom fieldtypes; however, there's an opportunity here to support custom fieldtypes.

First, in the blueprint there could be a field option `include` or something like that. And if it should be included, then you'd call a fieldtype method to get the data?

### Steps to reproduce

1. make a custom fieldtype
2. add to runway resource blueprint
3. try to save resource.

### Environment

Environment
Application Name: Zakat Foundation of America
Laravel Version: 10.23.0
PHP Version: 8.2.10
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 12
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.21.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
aryehraber/statamic-impersonator: 2.6.0
doublethreedigital/runway: 5.2.2
edalzell/forma: 2.1
jonassiewertsen/statamic-livewire: 2.12.0
statamic/seo-pro: 5.2.2
transformstudios/events: 5.0.1
transformstudios/front: 2.0.4
transformstudios/github: dev-main
transformstudios/neon: dev-feature/update-orphan-profile
transformstudios/review: 4.1.0
transformstudios/simple: 4.7.2

**Comment by edalzell** [comment]
OK I think custom fields ARE supported but because I don't want this particular custom field saved, there's an error.

PR incoming.

**Comment by duncanmcclean** [comment]
Yes, Runway does allow using custom fieldtypes but in your case its erroring because no column exists to persist it in the database.

**Comment by edalzell** [comment]
> Yes, Runway does allow using custom fieldtypes but in your case its erroring because no column exists to persist it in the database.

ya that's what my PR will be. This is not a bug but an FR.

**Comment by duncanmcclean** [comment]
This can already be achieved by using the `visibility: computed` option on your field.
