### ISSUE TITLE
Can't save resource when Statamic search is enabled

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/runway#345]
### Discussed in https://github.com/duncanmcclean/runway/discussions/344

<div type='discussions-op-text'>

<sup>Originally posted by **martink635** September 23, 2023</sup>
I need some help with setting this up. I am following the docs, and everything mostly works fine, but on saving I get this error:

```
[2023-09-23 12:54:34] local.ERROR: DoubleThreeDigital\Runway\Data\AugmentedModel::supplement(): Argument #1 ($data) must be of type array, null given, called in /statamic/vendor/doublethreedigital/runway/src/Search/Searchable.php on line 81 {"userId":"8d82ac72-df9a-485b-900a-6fd41bd61545","exception":"[object] (TypeError(code: 0): DoubleThreeDigital\\Runway\\Data\\AugmentedModel::supplement(): Argument #1 ($data) must be of type array, null given, called in /statamic/vendor/doublethreedigital/runway/src/Search/Searchable.php on line 81 at /statamic/vendor/doublethreedigital/runway/src/Data/AugmentedModel.php:26)
```

The model gets saved normally, but it throws this. Not sure what is the cause. I've tried and I can replicate it with a blueprint of just 1 title field and nothing else.

I think I missed a step somewhere, but can't find it.

Using the latest Statamic and Runway. I do have the Meilisearch addon, but the model in question is not being indexed.</div>

**Comment by duncanmcclean** [comment]
@martink635 Can you share your `search.php` config file? I can't reproduce this.

**Comment by martink635** [comment]
Of course. I am sorry if this was not clear enough, this I think only happens if you use the Meilisearch addon for Statamic. It might be an issue on their end as well.

https://statamic.com/addons/elvenstar/statamic-meilisearch

```
    'indexes' => [

        'default' => [
            'driver' => 'local',
            'searchables' => 'all',
            'fields' => ['title'],
        ],

        'recipes' => [
            'driver' => 'meilisearch',
            'searchables' => ['collection:recipes'],
            'fields' => ['title', 'description', 'locale', 'status'],
            'sites' => "all",
            'settings' => [
                'filterableAttributes' => ['locale', 'status'],
                'stopWords' => [],
            ],
        ],

    ],
```

If I remove the recipes index, everything works fine. I've pasted the full stack error log in the discussion reply as well.

**Comment by duncanmcclean** [comment]
I had a look a few days ago and I think there's something that needs to be changed in the Mellisearch driver. 

I think `$document->reference()` on [this line](https://github.com/elvenstar/statamic-meilisearch/blob/a9c1a0ca8fca81425568af05ba0dd33712e3c343/src/MeiliSearch/Index.php#L43) needs to be changed to `$document->getSearchReference()` which is used in the same place in the built-in [Algolia driver](https://github.com/statamic/cms/blob/4.x/src/Search/Algolia/Index.php#L47).

Would you be able to let me know if making that change fixes the issue?

**Comment by duncanmcclean** [comment]
I've opened a PR on the Mellisearch driver: https://github.com/elvenstar/statamic-meilisearch/pull/18

Since this issue isn't a bug with Runway itself, I'm going to close this issue now.

**Comment by martink635** [comment]
Thanks for this!

Sorry for the late reply, but the proposed change fixes this. 👍
