### ISSUE TITLE
paginate->withQueryString()

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/runway#349]
### Discussed in https://github.com/duncanmcclean/runway/discussions/348

<div type='discussions-op-text'>

<sup>Originally posted by **kevnk** September 29, 2023</sup>
I'm running the paginate with additional query params like `?category=family&sort=new_releases` and going to the next page replaces them with `?page=2` and the user loses their filtering. This can be easily solved with [Laravel's method `withQueryString`](https://laravel.com/docs/10.x/pagination#appending-query-string-values). I'm not sure you want to do this by default or if you want to add another param to the RunwayTag.

I can't think of any CONs to having it in there by default, but maybe there's a slight performance hit? 

I'm happy to send a pull request. 

Thanks!</div>

**Comment by duncanmcclean** [comment]
@kevnk This sounds like a bug, rather than a feature to me so I've converted it into an issue. 

If you're able to, a pull request would be great!

**Comment by kevnk** [comment]
Thanks for merging this @duncanmcclean — Unfortunately, it's not working for me... 

Here's my simplified version of code:

```
{{ books_scope = get:sort == 'new' ?  "sortByReleaseDate" : '' }}
{{ runway:book as="books" :scope="books_scope" paginate="true" limit="36" }}
    {{ paginate }}
        {{ links:all }}
            <div>{{ page }} ({{ url }})</div>                  
        {{ /links:all }}
    {{ /paginate }}
{{ /runway:book }}
```

So, when I'm on the URL with `?sort=new`, it sorts by release date, but all the pagination links only have the page param: eg. `?page=2` instead of what I'd hoped `?page=2&sort=new`

I've tried to find statamic's paginate tag or links:all tag to see if there's a bug on their side... 

Otherwise, I'm not sure what's up.

**Comment by kevnk** [comment]
This is how I've worked around it for now:

```
{{ url }}&{{$ http_build_query(request()->query()) $}}
```

**Comment by duncanmcclean** [comment]
@kevnk I've just tagged another release which seems to fix the issue - would you be able to give it a try?

**Comment by kevnk** [comment]
> @kevnk I've just tagged another release which seems to fix the issue - would you be able to give it a try?

Sure thing. I'll check it out Monday. Thanks!

**Comment by kevnk** [comment]
@duncanmcclean — v5.3.3 works beautifully. Nice work! Thank you! 🙏
