### ISSUE TITLE
Deleting items in the table view on HasMany field breaks

### ISSUE THREAD

**Issue by Jade-GG** [duncanmcclean/runway#380]
### Description

We are using the `table` view mode on a HasMany field. On the surface it appears to work fine: you can remove an item, you can add items with the popover view.

However, there seem to be a few issues with it:

- When first adding at least one item and then deleting any other random item, everything gets duplicated.
  - If you then succeed at saving these changes, your statamic backend page will be broken beyond repair, and you have to delete the duplicated entries manually from your raw data
- Sometimes, after deleting one item, the next deleted item does not correspond to the one that I tried to delete.

I wasn't able to quickly track this down in the code myself, hence the bug report instead.

### Steps to reproduce

1. Create a HasMany field on something, point it to your runway resource and select the `table` display mode
2. Select a few of your resources and save them into your something
3. Edit your something again, this time add a few of your resources and then delete one
4. Alakazam! Observe, as everything is now duplicated.

(you might only see a few duplications appear in the frontend, but deep down everything save from the actual removed item itself got duplicated)

### Environment

Environment
Application Name: [...]
Laravel Version: 10.32.1
PHP Version: 8.2.13
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: [...]
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.35.0 PRO

Statamic Addons
doublethreedigital/runway: 5.5.1
statamic/eloquent-driver: 2.10.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Taxonomies: file
Terms: eloquent

**Comment by duncanmcclean** [comment]
Hah, that's not fun!

Just a heads up: the Table mode for the HasMany fieldtype is being removed in Runway v6 (#360) since it's pretty complicated under the hood and not a lot of people use it.

**Comment by Jade-GG** [comment]
> Hah, that's not fun!
> 
> Just a heads up: the Table mode for the HasMany fieldtype is being removed in Runway v6 (#360) since it's pretty complicated under the hood and not a lot of people use it. Removing it will bring Runway more inline with Statamic Core.

Ah cool, that's one way to fix it 😁
