### ISSUE TITLE
Can't see belongsTo relationship on index w/o max_items

### ISSUE THREAD

**Issue by caseydwyer** [duncanmcclean/runway#391]
### Description

Currently, when you have a `belongsTo` field in a blueprint, the related model only shows on the index view when `max_items: 1` is explicitly defined for that field. Without that, the index is blank (but works as expected, on the show/edit view). My two cents here, is that it shouldn't be required for `belongsTo`, as it's redundant...but very possible this is working as intended for some reason and it's not a bug. If that's the case, maybe a simple addition to docs would be helpful?

## Without `max_items: 1` defined in BP:
![image](https://github.com/duncanmcclean/runway/assets/13950848/c325634f-46d3-4d56-9948-1f0cb7567db0)

## With `max_items: 1` defined in BP:
![image](https://github.com/duncanmcclean/runway/assets/13950848/b8a19432-f342-4cd3-86ab-e641dfce245f)

Thanks Duncan!

### Steps to reproduce

1. Setup two models, one with a `belongsTo` field to the other.
2. Exclude `max_items` from that field's blueprint.
3. Load index for the owned model, confirm that related record is missing.
4. Add `max_items: 1` to the blueprint, reload, see related record linked.

### Environment

Environment
Application Name: TF
Laravel Version: 10.39.0
PHP Version: 8.2.5
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: tf.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.3.5

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.1 PRO

Statamic Addons
doublethreedigital/runway: 5.6.0
...

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: file

**Comment by duncanmcclean** [comment]
As far as I know, you can only have an Eloquent `belongsTo` relationship to a single item.

If you need to relate to multiple models, surely the Has Many fieldtype is what you need?

**Comment by caseydwyer** [comment]
> As far as I know, you can only have an Eloquent belongsTo relationship to a single item.

Right, that's part of the equation here. That is, the `max_items: 1` **shouldn't be necessary**, since it's redundant—a `belongsTo`, by definition, has one maximum item. But until you explicitly add `max_items: 1` into the blueprint, the index view won't show that `belongsTo` relationship on the index—it just looks empty. Not sure what's causing that and also wasn't sure if that was expected behavior for some reason, or else I would've PR'd a fix.

That's what I was trying to show in those screenshots, but yeah—kind of a tricky thing to explain. Does that help clarify at all?

**Comment by duncanmcclean** [comment]
> > As far as I know, you can only have an Eloquent belongsTo relationship to a single item.
> 
> Right, that's part of the equation here. That is, the `max_items: 1` **shouldn't be necessary** IMHO, since it's redundant—a `belongsTo`, by definition, has one maximum item. But until you explicitly add `max_items: 1` into the blueprint, that `belongsTo` relationship won't be shown on the index—it just looks empty. Not sure what's causing that and also wasn't sure if that was expected behavior for some reason, or else I would've PR'd a fix.
> 
> That's what I was trying to show in those screenshots, but yeah—kind of a tricky thing to explain. In those 'shots, I didn't change anything _except_ to add/remove the `max_items: 1` in the blueprint. Does that help clarify at all?

Oh, okay! I believe it's because `max_items` is required for "relationship fieldtype" stuff under the hood in Statamic. Although, Runway *should* be defaulting that to 1 for the Belongs To fieldtype.

**Comment by caseydwyer** [comment]
> required for "relationship fieldtype" stuff under the hood in Statamic
Gotcha! Makes sense, and I wondered if that was maybe the case—just didn't know where to look in Statamic itself. 👍 I'll close this out, thanks for the clarification, Duncan!
